[target."cfg(all())"]
runner = "sudo -E"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]

[target.bpfel-unknown-none]
linker = "bpf-linker"
rustflags = [
  "--cfg=bpf_target_arch=\"x86_64\"",
  "-Cpanic=abort",
  "-Cdebuginfo=2",
  "-Clink-arg=--btf",
]

[target.bpfeb-unknown-none]
linker = "bpf-linker"
rustflags = [
  "--cfg=bpf_target_arch=\"x86_64\"",
  "-Cpanic=abort",
  "-Cdebuginfo=2",
  "-Clink-arg=--btf",
]
