[package]
name = "tails-pdp-userspace-pep"
version = "0.1.0"
edition.workspace = true

license.workspace = true

[dependencies]
tails-pdp-common = { path = "../tails-pdp-common", features = ["user"] }
tails-pdp-userspace-common = { path = "../tails-pdp-userspace-common" }

anyhow = { workspace = true, default-features = true }
aya = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[lib]
path = "src/lib.rs"
